name: Autograding Tests
on:
  workflow_dispatch:
  pull_request:

permissions:
  checks: write
  packages: read
  actions: write
  contents: write
jobs:
  run-autograding-tests:
    runs-on: ghcr.io/dmacc-cis289-spring-2025/github-classroom-python-template:latest
    container:
      image: ghcr.io/dmacc-cis289-spring-2025/github-classroom-python-template:latest
      options: --user vscode
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Run Precommit Hooks
      run: |
        cd $GITHUB_WORKSPACE
        ls -alh
        pre-commit
        pre-commit run --all-files
    - name: Run Pytest
      run: |
        pytest -v
