name: PreChecks
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-prechecks:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pre-commit
      run: |
        pre-commit run --all-files

    - name: Run Pytest
      run: |
        pytest -v

    - name: Run Ruff Check
      run: |
        ruff check

    - name: Cache pre-commit hooks
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
  # run-autograding-tests:
  #   runs-on: ubuntu-latest
  #   if: github.actor != 'github-classroom[bot]'
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #     # This is where you place your autograding tests
  #     # For more information on this runner, see the documentation at: https://github.com/classroom-resources/autograding-io-grader
  #     #
  #     # For example, you could run a test suite like this:
  #     # - name: Run tests
  #     #   uses: classroom-resources/autograding-io-grader@v1
  #     #     with:
  #     #       test-name: Addition Test
  #     #       id: addition-test
  #     #       command: "./bin/add.sh"
  #     #       input: 1 2
  #     #       expected-output: 3
  #     #       comparison-method: exact
  #     #       timeout: 10
  #   - name: Autograding Reporter
  #     uses: classroom-resources/autograding-grading-reporter@v1
  #     # For more information on this runner, see the documentation at https://github.com/classroom-resources/autograding-grading-reporter
  #     # To output the results of the tests, you can use the
  #     # autograding-grading-reporter action like this:
  #     # env:
  #     # ADDITION-TEST_RESULTS: "${{ steps.addition - test.outputs.result }}"
  #     #     with:
  #     #         runners: addition-test
